<script type="text/javascript">
$(document).ready(function() {
	tinymce.init({
		selector: '#textarea_{{$name}}',
		language: 'de',
		directionality: 'ltr',
		height: 500,
		theme: 'modern',
		plugins: [
			'advlist autolink lists link image charmap print preview hr anchor pagebreak',
			'searchreplace wordcount visualblocks visualchars code fullscreen',
			'insertdatetime media nonbreaking save table contextmenu directionality hr',
			'paste textcolor colorpicker textpattern imagetools codesample toc'
		],
		toolbar1: 'undo redo | insert | styleselect fontselect fontsizeselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
		toolbar2: 'print preview media fullscreen | forecolor backcolor | codesample charmap | ltr rtl',
		image_advtab: true,
		content_css: [
            '//fonts.googleapis.com/css?family=Alef|Arimo|Cardo|Caudex|David+Libre|Droid+Sans|Droid+Serif|Fira+Sans|Frank+Ruhl+Libre|GFS+Didot|GFS+Neohellenic|Heebo|Lato|Noto+Sans|Noto+Serif|Open+Sans|Roboto|Rubik|Secular+One|Slabo+27px|Source+Sans+Pro|Tinos|Ubuntu'
		],
        font_formats: 'Alef=alef;David=david;Lato=lato;Cardo=cardo;Tinos=tinos;Roboto=roboto;Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Georgia=georgia,palatino;Helvetica=helvetica;Impact=impact,chicago;Symbol=symbol;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats',
		fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt',
		charmap_append: [
            [0x591, 'Etnahta'],
            [0x592, 'Segol'],
            [0x593, 'Schalschelet'],
            [0x594, 'Zakef Katan'],
            [0x595, 'Zakef Gadol'],
            [0x596, 'Tipeha'],
            [0x597, 'Rewia'],
            [0x598, 'Zarka'],
            [0x599, 'Paschta'],
            [0x56A, 'Jetiw'],
            [0x56B, 'Tewir'],
            [0x56C, 'Geresch'],
            [0x56D, 'Geresch Mukdam'],
            [0x56E, 'Gerschajim'],
            [0x56F, 'Karnej Para'],
            [0x560, 'Telischa Gedola'],
            [0x561, 'Pazer'],
            [0x562, 'Atnah Hafuch'],
            [0x563, 'Munah'],
            [0x564, 'Mahapach'],
            [0x565, 'Mercha'],
            [0x566, 'Mercha Kefula'],
            [0x567, 'Darga'],
            [0x568, 'Kadma'],
            [0x569, 'Telischa Ketana'],
            [0x5AA, 'Jerah Ben Jomo'],
            [0x5AB, 'Ole'],
            [0x5AC, 'Iluj'],
            [0x5AD, 'Dehi'],
            [0x5AE, 'Zinor'],
            [0x5AF, 'Masora-Kreis'],
            [0x5B0, 'Schewa'],
            [0x5B1, 'Chatef Segol'],
            [0x5B2, 'Chatef Patach'],
            [0x5B3, 'Chatef Kametz'],
            [0x5B4, 'Hirik'],
            [0x5B5, 'Tzere'],
            [0x5B6, 'Segol'],
            [0x5B7, 'Patach'],
            [0x5B8, 'Kametz'],
            [0x5B9, 'Holam'],
            [0x5BA, 'Holam Haser für Waw'],
            [0x5BB, 'Kibutz'],
            [0x5BC, 'Dagesch oder Mapik'],
            [0x5BD, 'Meteg'],
            [0x5BE, 'Makaf'],
            [0x5BF, 'Rafe'],
            [0x5C0, 'Pasek'],
            [0x5C1, 'Schin-Punkt'],
            [0x5C2, 'Sin-Punkt'],
            [0x5C3, 'Sof Pasuk'],
            [0x5C4, 'oberer Punkt'],
            [0x5C5, 'unterer Punkt'],
            [0x5C6, 'Nun Hafucha'],
            [0x5C7, 'Kametz Katan'],
            [0x5D0, 'Aleph'],
            [0x5D1, 'Beth'],
            [0x5D2, 'Gimel'],
            [0x5D3, 'Daleth'],
            [0x5D4, 'He'],
            [0x5D5, 'Waw'],
            [0x5D6, 'Zajin'],
            [0x5D7, 'Chet'],
            [0x5D8, 'Tet'],
            [0x5D9, 'Jod'],
            [0x5DA, 'Schluss-Kaph'],
            [0x5DB, 'Kaph'],
            [0x5DC, 'Lamed'],
            [0x5DD, 'Schluss-Mem'],
            [0x5DE, 'Mem'],
            [0x5DF, 'Schluss-Nun'],
            [0x5E0, 'Nun'],
            [0x5E1, 'Samech'],
            [0x5E2, 'Ajin'],
            [0x5E3, 'Schluss-Pe'],
            [0x5E4, 'Pe'],
            [0x5E5, 'Schluss-Tzade'],
            [0x5E6, 'Tzade'],
            [0x5E7, 'Koph'],
            [0x5E8, 'Resch'],
            [0x5E9, 'Schin'],
            [0x5EA, 'Taw'],
            [0x5F0, 'jiddisches Doppel-Waw'],
            [0x5F1, 'jiddisches Waw-Jod'],
            [0x5F2, 'jiddisches Doppel-Jod'],
            [0x5F3, 'Geresch'],
            [0x5F4, 'Gerschajim']

        ]
	});

})
</script>
<div class='form-group' id='form-group-{{$name}}' style="{{@$form['style']}}">
	<label class='control-label col-sm-2'>{{$form['label']}}</label>
	<div class="{{$col_width?:'col-sm-10'}}">
		<textarea id='textarea_{{$name}}' id="{{$name}}" {{$required}} {{$readonly}} {{$disabled}} name="{{$form['name']}}" class='form-control' rows='5'>{{ $value }}</textarea>
		<div class="text-danger">{{ $errors->first($name) }}</div>
		<p class='help-block'>{{ @$form['help'] }}</p>
	</div>
</div>
