<?php
return [
    'email_footer'               => 'Bitte keine Email zurückschicken. Diese Email wurde automatisch von System generiert.',
    'login_message'              => 'Bitte einloggen.',
    'text_forgot_password'       => 'Passwort vergessen?',
    'page_title_login'           => 'Login Panel',
    'page_title_forgot'          => 'Password vergessen',
    'forgot_message'             => 'Bitte Emailadresse eingeben, um das Passwort zurückzusetzen.',
    "forgot_text_try_again"      => "Versuch dich nochmal einzuloggen?",
    'text_no_notification'       => "Du hast 0 Nachrichten",
    'text_view_all_notification' => 'Alles ansehen.',
    'label_button_profile'       => "Profil",
    'filter_dialog_title'        => 'Fortgeschrittenes Sortieren & Filtern',
    'there_is_no_option'        => 'Es gibt keine Möglichkeit diesen inputType einzustellen.',
    'no'                          => 'Nein.',

    'text_enter_the_password'     => 'Bitte gib dein Passwort ein, um die Session wiederherzustellen',
    'text_or_sign_in'             => 'oder als anderer Benutzer einloggen.',
    'text_default_add_new_module' => 'Neues :modul hinzufügen',
    'text_default_list_module'    => ':modul auflisten',
    'text_default_help_password'  => 'Mindestens 5 Zeichen oder leer lassen, falls das Passwort nicht verändert werden soll.',
    'text_default_help_upload'    => 'Unstützte Dateien: JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number'    => 'Bitte nur eine Zahl eingeben.',
    'text_default_help_email'     => 'Bitte eine Emailaddresse angeben.',
    'text_default_help_text'      => 'Bitte nur Buchstaben eingeben.',
    'text_default_help_url'       => 'Bitte eine URL angeben.',
    'text_dashboard'              => 'Instrumententafel',
    'text_prefix_option'          => '** Bitte wähle eine * aus',
    'text_loading'                => 'Bitte warten ...',

    'message_after_logout'    => 'Vielen Dank, bis später!',
    'message_forgot_password' => 'Du hast ein neues Passwort festgelegt, bitte schau in deine Email!',

    'page_not_found'      => 'Ups! Seite nicht gefunden!',
    'page_not_found_text' => 'Die Seite konnte nicht gefunden werden.',
    'page_not_found_tips' => '*  Bitte vergewissere dich, dass die URL richtig ist.<br/>
                * Bitte vergewissere dich, dass die Schritart richtig engestellt ist.<br/>
                * Vielleicht wurd die Seite, die du suchst vom Administrator gelöscht.<br/>
                * Du kannst mit Hilfe der Zurücktaste am Browser zurückgehen.<br/>',

    'log_try_view'            => 'Versuche die Daten :name in :module anzusehen.',
    'log_try_edit'            => 'Versuche die Daten :name in :module zu bearbeiten.',
    'log_try_add'             => 'Versuche die Daten in :module zu bearbeiten.',
    'log_try_add_save'        => 'Versuche die Daten :name in :module zu bearbeiten.',
    'log_try_delete'          => 'Versuche die Daten :name data in :module zu löschen.',
    'log_try_delete_selected' => 'Versuche ausgewählte Daten in :module zu löschen.',
    'log_try_delete_image'    => 'Versuche das Bild :name in :module zu löschen.',
    'log_try_update'          => 'Versuche die Daten :name in :module zu aktualisieren.',
    'log_add'                 => 'Neue Daten :name in :module hinzugefügt.',
    'log_update'              => 'Daten :name in :module aktualisiert.',
    'log_delete'              => 'Daten :name in :module gelöscht.',
    'log_delete_image'        => 'Bild :name in :module glöscht.',
    'log_login'               => ':email hat sich mit der IP :ip eingeloggt.',
    'log_forgot'              => 'Jemand mit der IP :ip hat versucht das Passwort für diese Email :email zurückzusetzen.',
    'log_logout'              => ':email ausloggen.',

    'alert_delete_selected'         => 'Bist du sicher, dass du alle ausgewählten Daten löschen willst?',
    'alert_delete_selected_success' => 'Ausgewählter Eintrag wurde entfernt!',
    'alert_bulk_action_button'      => 'Willst du wirklick',
    'alert_action'                  => 'Du hast :action erfolgreich ausgeführt!',
    'alert_add_data_success'        => 'Die Daten wurden hinzugefügt!',
    'alert_add_data_failed'         => 'Die Daten konnten nicht hinzugefügt werden!',
    'alert_update_data_success'     => 'Die Daten wirden aktualisiert!',
    'alert_update_data_failed'      => 'Die Daten konnten nicht aktualsiert werden.',
    'alert_delete_data_success'     => 'Die Daten wurden erfolgrich gelöscht!',
    'alert_want_to_logout'          => 'Willst du dich ausloggen?',
    'alert_warning'                 => "Oi Gewalt",
    'alert_danger'                  => 'Etwas ist schiefgelaufen ....',
    'alert_success'                 => 'Hat geklappt',
    'alert_info'                    => 'Information',
    'alert_primary'                 => 'Information',
    'alert_session_expired'         => 'Deine Session ist abgelaufen, bitte logge dich nochmal ein!',
    'alert_password_wrong'          => 'Dein Passwort ist falsch!',
    'alert_required'                => 'Bitte fülle alle benötigten Felder richtig aus.',
    'alert_error_ajax'              => 'Es ist etwas schief gelaufen, wir werden das reparieren!',
    'alert_validation_error'        => 'Bitte fülle das Formular richtig aus: :error',

    'add_data_page_title'    => ':module hinzufügen',
    'edit_data_page_title'   => ':module bearbeiten',
    'detail_data_page_title' => ':module Details',

    'default_module_description' => 'Liste der Daten',

    'delete_description_confirm' => "Diese Daten können nicht wiederhergestellt werden!",
    'delete_title_confirm'       => "Bist du sicher?",


    'action_show_data'       => 'Daten anzeigen',
    'action_add_data'        => 'Daten hinzufügen',
    'action_delete_selected' => 'Ausgewählte Daten löschen',

    'action_label'       => 'Aktion',
    'action_detail_data' => 'Details',
    'action_edit_data'   => 'Daten bearbeiten',
    'action_delete_data' => 'Löschen',


    'button_cancel'          => 'Abbrechen.',
    'button_add'             => 'Daten hinzufügen',
    'button_edit'            => 'Daten bearbeiten',
    'button_back'            => 'Zurück',
    'button_save'            => 'Speichern',
    'button_save_more'       => 'Speichern & mehr importieren',
    'button_import'          => 'Daten importieren',
    'button_export'          => 'Daten exportieren',
    'button_filter'          => 'Sortieren & Filtern',
    'button_close'           => 'Schließen',
    'button_submit'          => 'Abschicken',
    'button_logout'          => 'Ausloggen',
    'button_sign_in'         => 'Einloggen',
    'button_selected_action' => 'Stapelverarbeitung',
    'button_download_file'   => 'Date runterladen',
    'button_reset'           => 'Zurücksetzen',

    'export_dialog_title'            => "Daten exportieren",
    'export_dialog_filename'         => 'Dateiname',
    'export_dialog_help_filename'    => 'Du kannst die Daten nach einen Wünschen umbenennen.',
    'export_dialog_maxdata'          => "Maximale Daten",
    'export_dialog_help_maxdata'     => 'Minimum 1 und Maximum 100.000 Zeilen pro Export.',
    'export_dialog_columns'          => 'Spalten',
    'export_dialog_format_export'    => 'Exportformat',
    'export_dialog_show_advanced'    => 'Zeige weitere Exportmöglichkeiten',
    'export_dialog_page_size'        => 'Seitengröße',
    'export_dialog_set_default'      => 'Standart Seitengröße einstellen',
    'export_dialog_page_orientation' => 'Seitenausrichtung',

    'import_page_title'         => 'Daten importieren :module',
    'dashboard_default_text'    => 'Willkommen auf der Instrumententafel von: :appname',
    'form_back_to_list'         => 'Zurück zu Übersicht :module',
    'not_logged_in'             => 'Du bist nicht eingeloggt!',
    'menu_navigation'           => "Navigation",
    'table_data_not_found'      => "Keine Daten vorhanden",
    "notice_delete_file_upload" => "* Wenn du weitere Dateien hochladen willst, bitte zuerst die erste Datei löschen.",
    "file_broken"               => "Oh, sieht aus als wäre die Datei kaputt! Klicke auf Löschen und lade die Datei neu hoch.",

    'denied_access' => 'Du hast keine Berechtigung diesen Bereich zu betreten!',
    'denied_update' => 'Du hast keine Berechtigung diese Daten zu aktualisieren!',
    'denied_create' => 'Du hast keine Berechtigung diese Daten zu erstellen!',
    'denied_delete' => 'Du hast keine Berechtigung diese Daten zu löschen!',

    'user_image'           => 'Profilbild',
    'online'               => 'Online',
    'controller_route_404' => 'Controller / Route nicht gefunden',
    'home'                 => 'Home',

    'Privileges_Roles'    => 'Benutzerrechte',
    'Add_New_Privilege'   => 'Neue Benutzerrechte hinzufügen',
    'List_Privilege'      => 'List Privilege',
    'add_user'            => 'Nutzer hinzufügen',
    'List_users'          => 'Nutzer ansehen',
    'Menu_Management'     => 'Menuverwaltung',
    'Add_New_Setting'     => 'Neue Einstellung hinzufügen',
    'Add_New_Module'      => 'Neues Modul hinzufügen',
    'List_Module'         => 'Module auflisten',
    'Add_New_Statistic'   => 'Neue Statistik hinzufügen',
    'List_Statistic'      => 'Statistik ansehen',
    'Add_New_API'         => 'Neue API hinzufügen',
    'API_Generator'       => 'API Generator',
    'Statistic_Builder'   => 'Statistikgenerator',
    'Module_Generator'    => 'Modulgenerator',
    'settings'            => 'Einstellungen',
    'Users_Management'    => 'Nutzerverwaltung',
    'list_API'            => 'API ansehen (Dokumentation)',
    'Generate_Screet_Key' => 'Geheimen Schlüssel erzeugen',
    'Add_New_Email'       => 'Neue Email hinzufügen',
    'List_Email_Template' => 'Emailvorlagen ansehen',
    'Email_Templates'     => 'Emaivorlagen',
    'Log_User_Access'     => 'Nutzerzugriff protokollieren',
    'SUPERADMIN'          => 'SUPERADMIN',

    'click_here' => 'Hier klicken',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right'      => 'rechts',
    'left'       => 'links',

    'all_rights_reserved' => 'Alle Rechte vorbehalten',
    'copyright'           => 'Copyright',
    'powered_by'          => 'Unterstützt von',

    'notification_you_have'     => 'Du hast',
    'notification_notification' => 'Nachrichten',
    'notification_new'          => 'Du hst eine neue Nachricht!',

    'login_register_style'         => 'Login- und Registrierungseinstellungen',
    'email_setting'                => 'Emaileinstellungen',
    'application_setting'          => 'Systemeinstellungen',

    // table filter & sort 
    'filter_select_operator_type'  => 'Operator auswählen',
    'filter_ascending'             => 'AUFSTEIGEND',
    'filter_descending'            => 'ABSTEIGEND',
    'filter_equal_to'              => '=(gleich)',
    'filter_like'                  => 'WIE',
    'filter_not_like'              => 'NICHT WIE',
    'filter_greater_than_or_equal' => '>= (größer als oder gleich)',
    'filter_less_than_or_equal'    => '<= (kleiner als oder gleich)',
    'filter_less_than'             => '< (kleiner als)',
    'filter_greater_than'          => '> (größer als)',
    'filter_not_equal_to'          => '!= (ungleich)',
    'filter_in'                    => 'IN',
    'filter_not_in'                => 'NICHT IN',
    'filter_between'               => 'ZWISCHEN',
    'filter_sort_ascending'        => 'Aufsteigend sortieren',
    'filter_sort_descending'       => 'Absteigend sortieren',
    'filter_eg'                    => 'z.B.',
    'filter_lorem_ipsum'           => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search'                => 'Suche',
    'filter_from'                  => 'von',
    'filter_to'                    => 'bis',

    // confirmation
    'confirmation_yes'             => 'Ja!',
    'confirmation_no'              => 'Nein',

    //filemanager
    'chose_an_image'               => 'Bild auswählen',
    'chose_an_file'                => 'Datei auswählen ',
    
    //action confirmation
    'confirmation_title'            => 'Bestätigung',
    'confirmation_text'             => 'Bist du sicher?',
    'confirmButtonText'             => 'Ja',

    
    // privilege
    'privileges_name'               =>'Privilege Name',
    'privileges_super_admin'        =>'Super Admin',
    'privileges_standart_user'      =>'Normaler Benutzer',
    'privileges_ID'                 =>'ID',
    'set_as_superadmin'             =>'Zum Admin machen',
    'chose_theme_color_select'      =>'** Farbe des Backends auswählen.',
    'chose_theme_color'             =>'Farbe des Themes',
    'privileges_configuration'      =>'Nutzerrechte einstellen',
    'privileges_module_list_no'     =>'Nein.',
    'privileges_module_list_mod_names'=>'Name des Moduls',
    'privileges_module_list_view'   =>'Ansehen',
    'privileges_module_list_create' =>'Erstellen',
    'privileges_module_list_read'   =>'Lesen',
    'privileges_module_list_update' =>'Update',
    'privileges_module_list_delete' =>'Löschen',

];
